inherit_gem:
  retrieva-cop:
    - "config/rubocop.yml"
    # comment unless use rails cops
    - "config/rails.yml"

AllCops:
  TargetRubyVersion: 3.1
  # comment unless use rails cops
  TargetRailsVersion: 7.0
  Exclude:
    - bin/**
    - vendor/**/*
    - db/**/*

