require:
  - rubocop-rails
  - rubocop-minitest

AllCops:
  TargetRubyVersion: 3.1
  TargetRailsVersion: 7.0
  NewCops: enable
  Exclude:
    - bin/**
    - vendor/**/*
    - db/migrate/*
    - db/schema.rb
    - config.ru
    - tmp/**/*
    - public/**/*

